import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "../globals.css"
import { ClockIcon } from "@/components/ClockIcon"
import { Time } from "@/components/Time"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Live Content with Sanity and Next",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen">
          <header className="bg-gray-900 text-white py-4 px-6 flex items-center justify-between">
            <div className="flex items-center gap-4">
              <span className="text-2xl font-bold">
                React Conf Keynote 2024
              </span>
              <div className="bg-red-500 px-3 py-1 rounded-full text-sm font-medium animate-glow ">
                Live
              </div>
            </div>
            <div className="flex items-center gap-2">
              <ClockIcon className="h-5 w-5" />
              <span className="text-lg font-medium">
                <Time />
              </span>
            </div>
          </header>
          <main>{children}</main>
        </div>
      </body>
    </html>
  )
}
